data AlgDataType = Constr1 Type11 Type12
                 | Constr2 Type21
                 | Constr3 Type31 Type32 Type33
                 | Constr4

-- Construtores
--foo (Constr1 a b)   = ...
--foo (Constr2 a)     = ...
--foo (Constr3 a b c) = ...
--foo Constr4         = ...

